trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'azure-conn'

stages:

- stage: Dev
  jobs:
  - job: BuildAndDeployDev
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '.'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        artifactName: 'drop'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureServiceConnection)
        appName: 'sampletestapp-dev'
        package: '$(Build.ArtifactStagingDirectory)/app.zip'


- stage: Prod
  dependsOn: Dev
  jobs:
  - job: DeployProd
    steps:

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureServiceConnection)
        appName: 'sampletestapp'
        package: '$(Pipeline.Workspace)/drop/app.zip'